### ISSUE TITLE
loggedIn function removed

### ISSUE THREAD

**Issue by kimnzl** [Yeti-Media/angular-token-authentication#1]
In commit abd9a178dd7759f49a0feda3cf5d59aaa285a328 the loggedIn function has been removed, was this intentional? It is still listed in the read me.

```
-      loggedIn: function() {
-        return storage[getKey(accessTokenKey)] ? true : false;
```

**Comment by ntreadway** [comment]
@kimnzl Not sure, I will take a look as I am taking over this project. Thanks!

**Comment by ntreadway** [comment]
@kimnzl After reviewing it looks like the loggedIn function is not needed anymore.
You can use sessionHandler.getAccessToken() to do the same.

``` js
sessionHandler.getAccessToken();
```
